VotingApp/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

urlpatterns += [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/register/', views.register, name='register'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password-change/',
         auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password-change/done/',
         auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password-reset/',
         auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

app/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('create_poll', views.create_poll, name='create_poll'),
    path('github_redirect', views.github_redirect, name='github_redirect'),
    path('twitter_redirect', views.twitter_redirect, name='twitter_redirect'),
    path('fcc_redirect', views.fcc_redirect, name='fcc_redirect'),
    path('my_polls', views.my_polls, name="my_polls"),
    path('share_twitter', views.share_twitter, name='share_twitter'),
    path('delete/<int:question_id>/', views.delete_poll, name='delete'),
]

app/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _

CHOICE_ORDER_OPTIONS = (
    ('content', _('Content')),
    ('random', _('Random')),
    ('none', _('None'))
)


class Question(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    question_text = models.CharField(max_length=200, default="")
    pub_date = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    def publish(self):
        self.pub_date = timezone.now()
        self.save()

    def __str__(self):
        return '{0} by {1}'.format(self.question_text, self.user)


class Choice(models.Model):
    question = models.ForeignKey(Question,
                                 on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

app/templates/app/create_poll.html
{% extends "base.html" %}
{% block title %}
    create poll
{% endblock title %}
{% block content %}
    <form class="form-horizontal" method="POST" action="">
        {% csrf_token %}
        <div class="row spacer">
            <div class="col-2">
                <label>{{questionform.question_text.label}}</label>
            </div>
            <div class="col-4">
                <div class="input-group">
                    {{questionform.question_text}}
                </div>
            </div>
        </div>
        {{formset.management_form}}
        {% for form in formset %}
            <div class="row form-row spacer">
                <div class="col-2">
                    <label>{{form.choice_text.label}}</label>
                </div>
                <div class="col-4">
                    <div class="input-group">
                        {{form.choice_text}}
                        <div class="input-group-append">
                            <button type="button" class="btn btn-success add-form-row">+</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="row spacer">
            <div class="col-4 offset-2">
                <button type="submit" class="btn btn-block btn-primary">Create</button>
            </div>
        </div>
    </form>
{% endblock content %}

app/templates/app/detail.html
{% extends "base.html" %}
{% block title %}
{% endblock %}
{% block content %}
    <h1>{{question.question_text}}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'app:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" class="" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
        <input type="submit" class="btn btn-primary" value="Vote" />
    </form>
    <div class="row spacer">
        {% if request.user == question.user %}
            <a href="{% url "app:delete" question.id %}" class="btn btn-danger">Delete this Poll</a>
        {% endif %}
    </div>
{% endblock %}

app/templates/app/list.html
{% extends "base.html" %}
{% block title %}

{% endblock %}
{% block content %}
    <h1>Django-voting</h1>
    <h3>Below are polls hosted by Django-voting</h3>
    <h3>Select a poll to see the results {% if user.is_authenticated %}and vote,<a href="{% url 'app:add_new_question_choice' %}">or make a new poll!</a>{% endif %}</h3>
    {% if latest_question_list %}
        <ul class = "list-group">
            {% for question in latest_question_list %}
                <li class = "list-group-item">
                    <a href="{% url 'app:detail' question.id  %}">
                    {{question.question_text}}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available</p>
    {% endif %}
{% endblock %}

app/templates/app/my_polls.html
{% extends "base.html" %}
{% block title %}
{% endblock %}
{% block content %}
    <div>
        {% for poll in polls %}
		    <ul class = "list-group">
		        <li class = "list-group-item">
		                <a href="{% url 'app:detail' poll.id  %}">{{poll.question_text}}</a> by {{request.user}}
		        </li>
		    </ul>
        {% endfor %}
    </div>
{% endblock %}

app/templates/app/question_list.html
{% extends "base.html" %}
{% block title %}

{% endblock %}
{% block content %}
    <h1>Django-voting</h1>
    <h3>Below are polls hosted by Django-voting</h3>
    <h3>Select a poll to see the results {% if user.is_authenticated %}and vote,<a href="{% url 'app:create_poll' %}">or make a new poll!</a>{% endif %}</h3>
    {% if latest_question_list %}
        <ul class = "list-group">
            {% for question in latest_question_list %}
                <li class = "list-group-item">
                    <a href="{% url 'app:detail' question.id  %}">
                    {{question.question_text}}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available</p>
    {% endif %}
    {% endblock %}

app/templates/app/results.html
{% extends "base.html" %}
{% load staticfiles %}
{% load social_share %}
{% block title %}

{% endblock %}
{% block content %}
<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/0.2.0/Chart.min.js" type="text/javascript"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js" type="text/javascript"></script>
    <div class = "row">
        <div class = "col-md-5">
            <p hidden id = "votes">{{choice.votes}}</p>
            <h1>{{question.question_text}}</h1>
            <ul>
                {% for choice in question.choice_set.all %}
                    <li id = "votes">{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
                {% endfor %}
            </ul>
            <a href="{% url 'app:detail' question.id %}">Vote again?</a>
        </div>
        <div class = "col-md-5 col-md-offset-2">
            <canvas id = "chart" width="500" height="300"></canvas>
                <script>
                        $(document).ready(function(){
                        var votes = $("#votes").text();
                        var data = {
                            labels:[
                                // got this from https://stackoverflow.com/a/43706426
                                {% for choice in question.choice_set.all %}
                                    "{{choice.choice_text}}",
                                {% endfor %}
                            ],
                            datasets:[
                                {
                                    data:[{% for choice in question.choice_set.all %} "{{choice.votes}}", {% endfor %}],
                                    backgroundColor:[{% for color in colors %}"{{color}}",{% endfor %}]
                                }
                            ]
                        };
                        console.log(votes);
                        var ctx = document.getElementById("chart").getContext("2d");
                        var doughnutChart = new Chart(ctx,{
                            type:'doughnut',
                            data:data
                        });
                    });
                </script>

        </div>
        <br>
    </div>
    <div class="row">
        <a href="{% url "app:share_twitter" %}" class = "btn btn-twitter">Share on Twitter</a>
    </div>
{% endblock %}