VotingApp/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

urlpatterns += [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/register/', views.register, name='register'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password-change/',
         auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password-change/done/',
         auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password-reset/',
         auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

app/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('create_poll', views.create_poll, name='create_poll'),
    path('github_redirect', views.github_redirect, name='github_redirect'),
    path('twitter_redirect', views.twitter_redirect, name='twitter_redirect'),
    path('fcc_redirect', views.fcc_redirect, name='fcc_redirect'),
    path('my_polls', views.my_polls, name="my_polls"),
    path('share_twitter', views.share_twitter, name='share_twitter'),
    path('delete/<int:question_id>/', views.delete_poll, name='delete'),
]

app/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-social.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class = "container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{% url 'app:index' %}">Django Voting</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'app:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'app:my_polls' %}">My Polls</a>
                        </li>

                        <li class="nav-item">
                        <a class="nav-link disabled" href="{% url "app:create_poll" %}">New Poll</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{user}}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item btn btn-success" href="{% url 'logout' %}?next={{request.url}}">Sign Out</a>
                            </div>
                        </li>
                    {% else %}
                        <li class = "nav-item">
                            <a class = "nav-link disabled" href="{% url 'login' %}?next={{request.url}}">Sign in</a>
                        </li>
                        <li class = "nav-item">
                            <a class = "nav-link disabled" href="{% url 'register' %}">Register</a>
                        </li>
                        <li class = "nav-item">
                            <a href="{% url 'social:begin' 'twitter' %}" class = "btn btn-block btn-twitter">
                                Sign in with Twitter
                            </a>
                        </li>
                    {% endif %}
                    </ul>
                </div>
            </nav>
            <div class = "jumbotron">
                {% block content %}

                {% endblock %}
            </div>
            {% include "footer.html" %}
    </div>

</body>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
  <script type="text/javascript" src="{% static "js/app.js" %}"></script>
</html>

app/templates/footer.html
<p>This "django-Voting" app is build by <a href="{% url 'app:twitter_redirect' %}">@CruiseDevice</a> of freecodecamp</p>
<p>following is the instructions of <a href="{% url 'app:fcc_redirect' %}">"Basejump: Build a Voting App | Free Code Camp."</a></p>
<p>Github repository: <a href="{% url 'app:github_redirect' %}">CruiseDevice</a></p>